name        : first-class-instances
synopsis    : First class typeclass instances
description : See the README file in the project repository
version     : 0.1.0.0
category    : Language
git         : "https://gitlab.com/thematten/first-class-instances"
license     : BSD3
author      : "Matej Nižník"
maintainer  : "matten@tuta.io"
copyright   : "2019 Matej Nižník"

extra-source-files : [README.md, ChangeLog.md]

dependencies :
- base             >=4.7     && <5
- Cabal  # TODO: ghcide shouldn't need this for Setup.hs
- containers       >=0.6.0.1 && <0.7
- template-haskell >=2.14    && <2.16

library : { source-dirs : src }

tests :
  first-class-instances-test :
    main         : Spec.hs
    source-dirs  : test
    ghc-options  :
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies :
    - first-class-instances
    - hspec          >=2.7.1 && <3
    - hspec-discover >=2.7.1 && <3

ghc-options :
- -ferror-spans
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wmissing-export-lists
- -Widentities
- -Wredundant-constraints
- -Wpartial-fields
- -Wcompat

default-extensions :
- BlockArguments
- ConstraintKinds
- DataKinds
- DuplicateRecordFields
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoStarIsType
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- RecordWildCards
- RoleAnnotations
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns
