name        : improvised
synopsis    : First class typeclass instances
description : See the README file in the project repository
version     : 0.1.0.0
category    : Language
git         : "https://gitlab.com/thematten/first-class-instances"
license     : BSD3
author      : "Sandy Maguire"
maintainer  : "sandy@sandymaguire.me"
copyright   : "2020 Sandy Maguire"

extra-source-files : [README.md, ChangeLog.md]

dependencies :
- base             >=4.7     && <5
- containers       >=0.6.0.1 && <0.7
- template-haskell >=2.14    && <2.15
- transformers
- lens

library :
  source-dirs : src
  other-modules:
    - FCI.Control.Applicative
    - FCI.Control.Monad
    - FCI.Data.Functor
    - FCI.Internal
    - FCI.Internal.TH
    - FCI.Internal.Types
    - MockableImpl
    - THStuff

tests :
  first-class-instances-test :
    main         : Spec.hs
    source-dirs  : test
    ghc-options  :
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies :
    - first-class-instances

ghc-options :
- -ferror-spans
- -Wall
# - -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Widentities
- -Wredundant-constraints
- -Wpartial-fields
- -Wcompat

default-extensions :
- BlockArguments
- ConstraintKinds
- DataKinds
- DuplicateRecordFields
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoStarIsType
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- RecordWildCards
- RoleAnnotations
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns
