-- | Core types of first class instances.
module FCI.Internal.Types (
    Inst
  , Dict
  ) where

import Data.Kind

-------------------------------------------------------------------------------
-- | Type family that maps constraint to it's first class representation -
-- should be generally used instead of it's concrete result.
--
-- TODO: example
type family Inst (c :: Constraint) = (t :: Type) | t -> c

-------------------------------------------------------------------------------
-- | Data family instances of which are generated by TH for normal class
-- constraints (see 'FCINew.TH.mkInstRep'). Do not write these by hand,
-- instead, create new instance of 'Inst' mapping to separate datatype.
--
-- TODO: format of generated instance
data family Dict :: Constraint -> Type
