module FCI.Core (
    Inst
  , Dict
  , Internal.inst
  , (Internal.==>)
  , Internal.mkInst
  , Internal.plugin
  ) where

import qualified FCI.Internal as Internal

-------------------------------------------------------------------------------
-- | Type of constraint representation.
--
-- TODO: doc
type Inst c = Internal.Inst c

-------------------------------------------------------------------------------
-- | Type of class representation generated by 'mkInst'.
--
-- TODO: doc
type Dict = Internal.Dict