{-# options_ghc -Wno-unused-imports #-}

module FCI (
    Inst
  , Dict
  , Internal.inst
  , (Internal.==>)
  , Internal.Newtype
  , Internal.mkInst
  , module M
  ) where

import qualified FCI.Internal.Definitions as Internal
import qualified FCI.Internal.TH          as Internal

import FCI.Control.Applicative as M
import FCI.Control.Monad       as M
import FCI.Data.Functor        as M

-------------------------------------------------------------------------------
-- | Type of constraint representation.
---
-- TODO: doc
type Inst c = Internal.Inst c

-------------------------------------------------------------------------------
-- | Type of class representation generated by 'mkInst'.
--
-- TODO: doc
type Dict = Internal.Dict
